apiVersion: cloud.ibm.com/v1alpha1
kind: BillOfMaterial
metadata:
  name: 704-cp-waiops-infra-automation
spec:
  modules:
    - name: ocp-login
    - name: gitops-cp-catalogs-waiops-aimgr
    - name: olm
    - name: sealed-secret-cert
    - name: gitops-repo
    - name: argocd-bootstrap
    - name: gitops-console-link-job

    - name: gitops-cp-waiops-infra-automation
      variables:
        - name: namespace
          value: cp4waiops
        - name: storageclass
          value: portworx-rwx-gp-sc
        - name: storageClassLargeBlock
          value: portworx-rwx-gp-sc